export const mainInfo = {
  movie: [
    {
      source: '/src/image/movie/Red_one_2024.jpg',
      addDate: '3 дня назад',
      date: '2025',
      view: '43546',
      name: 'Красный (2024)',
      time: '02:20:30',
      genre: 'боевики',
      rating: 4,
      country: 'США',
    },
    {
      source: '/src/image/movie/paranoya.jpg',
      addDate: '1 дня назад',
      date: '2024',
      view: '43766',
      name: 'Паранойя (2024)',
      time: '02:12:23',
      genre: 'ужасы',
      rating: 5,
      country: 'Великобритание',
    },
    {
      source: '/src/image/movie/Holop_paris.jpg',
      addDate: '9 дня назад',
      date: '2023',
      view: '9866',
      name: 'Холоп из Парижа (2024)',
      time: '02:03:54',
      genre: 'комедия',
      rating: 4,
      country: 'Россия',
    },
    {
      source: '/src/image/movie/Ulybka_2.jpg',
      addDate: '1 дня назад',
      date: '2020',
      view: '36546',
      name: 'Улыбка 2 (2024)',
      time: '02:20:36',
      genre: 'ужасы',
      rating: 5,
      country: 'США',
    },
    {
      source: '/src/image/movie/igra_smerti.jpg',
      addDate: '3 дня назад',
      date: '2025',
      view: '2446',
      name: 'Игра смерти (2023)',
      time: '02:20:03',
      genre: 'драмы',
      rating: 4,
      country: 'Южная Корея',
    },
    {
      source: '/src/image/movie/legenda.jpg',
      addDate: '7 дня назад',
      date: '2022',
      view: '754546',
      name: ' Легенда (2024)',
      time: '02:20:30',
      genre: 'боевик',
      rating: 3,
      country: 'Китай',
    },
    {
      source: '/src/image/movie/pingvin.jpg',
      addDate: '5 дня назад',
      date: '2025',
      view: '424',
      name: ' Пингвин (2024)',
      time: '02:10:00',
      genre: 'боевик',
      rating: 5,
      country: 'США',
    },
    {
      source: '/src/image/movie/professional.jpg',
      addDate: '12 дня назад',
      date: '2024',
      view: '4346',
      name: 'Профессионал (2024)',
      time: '02:40:40',
      genre: 'боевик',
      rating: 4,
      country: 'Великобритание',
    },
  ],
  cartoon: [
    {
      source: '/src/image/cartoon/dikiy_robot.jpg',
      date: '3 дня назад',
      view: '432546',
      name: 'Дикий робот (2024)',
      time: '02:50:30',
      genre: 'полнометражка',
      rating: 5,
    },
    {
      source: '/src/image/cartoon/bikini_bottom.jpg',
      date: '1 дня назад',
      view: '433766',
      name: 'Бикини-Боттом: Фильм Сэнди Чикс',
      time: '01:15:30',
      genre: 'полнометражка',
      rating: 3,
    },
    {
      source: '/src/image/cartoon/gatkiy_4.jpg',
      date: '9 дня назад',
      view: '239866',
      name: 'Гадкий я 4 (2024)',
      time: '02:00:30',
      genre: 'полнометражка',
      rating: 4,
    },
    {
      source: '/src/image/cartoon/golovolomka_2.jpg',
      date: '1 дня назад',
      view: '366546',
      name: 'Головоломка 2 (2024)',
      time: '01:50:30',
      genre: 'полнометражка',
      rating: 5,
    },
    {
      source: '/src/image/cartoon/kak_prirycit_bizon.jpg',
      date: '3 дня назад',
      view: '352446',
      name: 'Как приручить бизона (2024)',
      time: '02:20:30',
      genre: 'полнометражка',
      rating: 4,
    },
    {
      source: '/src/image/cartoon/kung-fu_tiger.jpg',
      date: '7 дня назад',
      view: '754546',
      name: ' Кунг-фу тигр (2022)',
      time: '01:30:30',
      genre: 'полнометражка',
      rating: 5,
    },
    {
      source: '/src/image/cartoon/moana_2.jpg',
      date: '5 дня назад',
      view: '735424',
      name: 'Моана 2 (2024)',
      time: '01:40:30',
      genre: 'полнометражка',
      rating: 4,
    },
    {
      source: '/src/image/cartoon/transformer_one.jpg',
      date: '12 дня назад',
      view: '90 4346',
      name: 'Трансформеры: Начало (2024)',
      time: '02:00:30',
      genre: 'полнометражка',
      rating: 4,
    },
  ],
  library: [
    {
      source: '/src/image/library/yowsan_ysly_sahra.jpg',
      date: '3 месяца назад',
      view: '1766',
      name: 'Yowşan Ysly Sähra',
    },
    {
      source: '/src/image/library/duralga.jpg',
      date: '3 месяца назад',
      view: '915',
      name: 'Duralga',
    },
    {
      source: '/src/image/library/kamilligin_yolunda.jpg',
      date: '4 месяца назад',
      view: '1196',
      name: 'Kämilligiň ýolunda',
    },
    {
      source: '/src/image/library/hummet_hassasy.jpg',
      date: '4 месяца назад',
      view: '888',
      name: 'HÜMMET HASASY',
    },
    {
      source: '/src/image/library/syrdas_gerek.jpg',
      date: '9 месяцев назад',
      view: '3982',
      name: 'Syrdaş gerek',
    },
    {
      source: '/src/image/library/medet_berewer.jpg',
      date: '9 месяцев назад',
      view: '1576',
      name: 'Medet berewer',
    },
    {
      source: '/src/image/library/kalbymyn_owazy.jpg',
      date: '11 месяцев назад',
      view: '3392',
      name: 'Kalbymyň Owazy',
    },
    {
      source: '/src/image/library/caga_eziz_edebi_ondanam_eziz.jpg',
      date: '1 год назад',
      view: '5843',
      name: 'Çaga eziz, edebi ondan hem eziz',
    },
  ],
  music: [
    {
      name: 'Akmuhammet Hanow',
      source: 'src/image/music/akmuhammet_hanow.jpg',
    },
    {
      name: 'Azat Durdyýew',
      source: 'src/image/music/azat_durdyyew.jpg ',
    },
    {
      name: 'Emirgen',
      source: 'src/image/music/emirgen.jpg',
    },

    {
      name: 'Mansur Şaripow',
      source: 'src/image/music/mansur_saripow.jpg',
    },
    {
      name: 'Rosh Sazz',
      source: 'src/image/music/rosh_sazz.jpg',
    },
    {
      name: 'Shahzod Gulmyradow',
      source: 'src/image/music/shahzod_gulmyradow.jpg',
    },
  ],
  video: [
    {
      name: 'Rosh sazz Ft Hemra Yazgylyjow - Gerekdal',
      source: 'src/image/videoclip/102036bOMCZ3lP5p.jpg',
      date: '6 дней назад',
      view: '7310',
      time: '00:03:30',
      genre: 'Turkmen aýdymlary',
      rating: 5,
    },
    {
      name: 'Amon music (Agajan Igdirow) - Bas gaza',
      source: 'src/image/videoclip/102002gWqmTVfJEM.jpg',
      date: '3 недели назад',
      view: '10919',
      time: '00:02:15',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
    {
      name: 'Akmuhammet Hanow - Çeşmeler',
      source: 'src/image/videoclip//101995ELu0IQ2LLb.jpg',
      date: '3 недели назад',
      view: '11222',
      time: '00:02:05',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
    {
      name: 'Akmuhammet Hanow - Balam',
      source: 'src/image/videoclip//101994bUD0aGG7rF.jpg',
      date: '3 недели назад',
      view: '5544',
      time: '00:03:15',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
    {
      name: 'Akmuhammet Hanow - Seretmez',
      source: 'src/image/videoclip//101994bUD0aGG7rF.jpg',
      date: '3 недели назад',
      view: '3433',
      time: '00:02:45',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
    {
      name: 'Akmuhammet Hanow - Kakaň Gyzy',
      source: 'src/image/videoclip//101992NB8VNg72pZ.jpg',
      date: '3 недели назад',
      view: '4957',
      time: '00:03:55',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
    {
      name: 'Akmuhammet Hanow - Dilber',
      source: 'src/image/videoclip//101994bUD0aGG7rF.jpg',
      date: '3 недели назад',
      view: '2510',
      time: '00:02:55',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
    {
      name: 'Akmuhammet Hanow - Haraýym Döndi',
      source: 'src/image/videoclip//101994bUD0aGG7rF.jpg',
      date: '3 недели назад',
      view: '2004',
      time: '00:03:45',
      genre: 'Turkmen aýdymlary',
      rating: 4,
    },
  ],
  comedy: [
    {
      name: 'Yagshy matrisa kinoda 😂',
      source: 'src/image/videocomedy/100794LM61z26PCs.jpg',
      date: '2 месяца назад',
      view: '125264',
      time: '00:12:15',
      genre: 'Gülki dünýäsi',
      rating: 5,
    },
    {
      name: 'Aýdaly Şatlyk Gurbannazarow bilen Merdan Annamuhammedow',
      source: 'src/image/videocomedy/100794LM61z26PCs.jpg',
      date: '7 месяцев назад',
      view: '112534',
      time: '00:30:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
    {
      name: 'Между двумя папоротниками - Тила Текила и Дженнифер Энистон',
      source: 'src/image/videocomedy/100797W4Qig548iD.jpg',
      date: '7 месяцев назад',
      view: '53970',
      time: '00:20:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
    {
      name: 'Между двумя папоротниками - Натали Портман',
      source: 'src/image/videocomedy/101732ah0zw4wEyp.jpg',
      date: '7 месяцев назад',
      view: '38626',
      time: '00:12:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
    {
      name: 'Между Двумя Папоротниками Уилл Фарелл',
      source: 'src/image/videocomedy/100797W4Qig548iD.jpg',
      date: '7 месяцев назад',
      view: '42096',
      time: '00:42:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
    {
      name: 'Между двумя папоротниками - Брюс Уиллис.',
      source: 'src/image/videocomedy/101732ah0zw4wEyp.jpg',
      date: '7 месяцев назад',
      view: '34498',
      time: '00:32:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
    {
      name: 'Зак Галифианакис и Хиллари Клинтон - Между Двумя Папоротниками ',
      source: 'src/image/videocomedy/100793gCX3mMFlG4.jpg',
      date: '7 месяцев назад',
      view: '56617',
      time: '00:22:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
    {
      name: 'Между двумя папоротниками - Стив Каррел',
      source: 'src/image/videocomedy/101732ah0zw4wEyp.jpg',
      date: '7 месяцев назад',
      view: '30523',
      time: '00:32:15',
      genre: 'Gepleşikler',
      rating: 5,
    },
  ],
  cook: [
    {
      name: 'Ussat aşpez(2-nji tapgyr 3-nji tapgyr)',
      source: 'src/image/videocook/101943Bf3yFo6vNO.jpg',
      date: '2 дня назад',
      view: '1242',
      time: '00:12:00',
      genre: 'Tiz tagam',
      rating: 5,
    },
    {
      name: 'Ussat aşpez (2-nji tapgyr 2-nji bölüm)',
      source: 'src/image/video/101996ojVzOErU3F.jpg',
      date: '3 недели назад',
      view: '14242',
      time: '00:15:00',
      genre: 'Tiz tagam',
      rating: 5,
    },
    {
      name: 'Ussat Aşpez (2-nji tapgyr 1-nji)',
      source: 'src/image/videocook/101943Bf3yFo6vNO.jpg',
      date: '1 месяц назад',
      view: '11222',
      time: '00:11:00',
      genre: 'Tiz tagam',
      rating: 5,
    },
    {
      name: 'Ussat aşpez(Täze ýyl sany)',
      source: 'src/image/videocook/101935GY9Knc0ubs.jpg',
      date: '1 месяц назад',
      view: '15169',
      time: '00:15:00',
      genre: 'Tiz tagam',
      rating: 5,
    },
    {
      name: 'Я сделал пиццу как итальянский ПИЦЦА ШЕФ. Неаполитанская пицца в обычной духовке',
      source: 'src/image/videocook/99681x5K3sXICzh.jpg',
      date: '1 год назад',
      view: '3433',
      time: '00:52:00',
      genre: 'Hamyrly nahar',
      rating: 5,
    },
    {
      name: 'Pomidoro',
      source: 'src/image/videocook/99206eF7ofEM1iJ.jpg',
      date: '1 год назад',
      view: '181431',
      time: '00:22:00',
      genre: 'Hamyrly nahar',
      rating: 5,
    },
    {
      name: 'Doragly banan',
      source: 'src/image/videocook/986033mKcSncBKE.jpg',
      date: '1 год назад',
      view: '212018',
      time: '00:10:00',
      genre: 'Ftukty',
      rating: 5,
    },
    {
      name: 'CHizburger',
      source: 'src/image/videocook/9857729pe5XcnwR.jpg',
      date: '1 год назад',
      view: '191445',
      time: '00:12:00',
      genre: 'Etli nahar',
      rating: 5,
    },
  ],
  health: [
    {
      name: 'Чем пахнет РАК- Запомните эти ТРИ запаха! Будьте бдительны! Начальные симптомы рака',
      source: 'src/image/videohealth/91070rXlxEVK051.jpg',
      date: '2 года назад',
      view: '100099',
    },
    {
      name: 'Хватит работать - учимся отдыхать! -Как нужно правильно отдыхать',
      source: 'src/image/videohealth/910699JwJBheZuE.jpg',
      date: '2 года назад',
      view: '43220',
    },
    {
      name: 'Секрет молодости! -Инструкция по омоложению -7 советов, как выглядеть моложе своих лет',
      source: 'src/image/videohealth/91068JUZ2F6euSQ.jpg',
      date: '7 месяцев назад',
      view: '58704',
    },
    {
      name: 'Сахар - это белая смерть!-Как отказаться от сладкого',
      source: 'src/image/videohealth/91067Mjj2rgM8Tl.jpg',
      date: '2 года назад',
      view: '41730',
    },
    {
      name: 'Проблемы с памятью, что делать- Как правильно активировать свою память',
      source: 'src/image/videohealth/91066s1LHgIRRev.jpg',
      date: '2 года назад',
      view: '44361',
    },
    {
      name: 'Как улучшить зрение в домашних условиях- 5 эффективных практик для улучшения зрения',
      source: 'src/image/videohealth/91065TjiEUOzuHZ.jpg',
      date: '2 года назад',
      view: '50247',
    },
    {
      name: 'Как снять боль в спине- 3 практики для здорового позвоночника',
      source: 'src/image/videohEALTH/91064m3OIar3NYl.jpg',
      date: '2 года назад',
      view: '38065',
    },
    {
      name: 'Как очистить свой организм-',
      source: 'src/image/videoHEALTH/91063CP6UPxKDjQ.jpg',
      date: '2 года назад',
      view: '38984',
    },
  ],
  interest: [
    {
      name: 'Durmuşy kyssalar',
      source: 'src/image/videointerest/101730maMNP4FcRB.jpg',
      date: '2 месяца назад',
      view: '3245',
    },
    {
      name: 'MAHIRLI OYMELER - OGULBIBI REYIMOWA (1 NJI BOLUM)',
      source: 'src/image/videointerest/101513aR82O8zyad.jpg',
      date: '5 месяца назад',
      view: '3347',
    },
    {
      name: 'Добро пожаловать в захватывающий мир гастрономии с Горячим Шоу «Рецепты от Джемалы»!',
      source: 'src/image/videointerest/101365QZ15Q9VhDg.jpg',
      date: '5 месяца назад',
      view: '46665',
    },
    {
      name: 'Интервью с Джемал Байрамовой, которая имеет три вида бизнеса',
      source: 'src/image/videointerest/101313Z2v0XMZIRM.jpg',
      date: '3 месяца назад',
      view: '1310',
    },
    {
      name: 'Интервью с Керимовой Джамиля Бизнес леди, основательница коворкинг центра “Ish nokady”',
      source: 'src/image/videointerest/101205s3pQAipcse.jpg',
      date: '2 месяца назад',
      view: '1767',
    },
    {
      name: 'Интервью с Ирадой-Мяхри Ахмедовой',
      source: 'src/image/videointerest/101138cNMFFRVAyQ.jpg',
      date: '6 месяца назад',
      view: '6247',
    },
    {
      name: '«Клубничный рай» от Лейли',
      source: 'src/image/videointerest/101137znVVekbVWB.jpg',
      date: ' 2 месяцев назад',
      view: '4260',
    },
    {
      name: 'Интервью с Рамилей Рамазановой',
      source: 'src/image/videointerest/101136t0JCBXSk6t.jpg',
      date: ' 3 месяцев назад  ',
      view: '9984',
    },
  ],
  karaoke: [
    {
      name: 'Yulduz Usmonova - Sanamgina',
      source: 'src/image/videokaraoke/1020345S8WVtqghk.jpg',
      date: '1 неделю назад',
      view: '2256',
    },
    {
      name: 'Tujhe Dekha To Ye Jaana Sanam',
      source: 'src/image/videokaraoke/102030rDEVU4Xele.jpg',
      date: '1 неделю назад',
      view: '1459',
    },
    {
      name: 'Seni Unutmaya Ömrüm Yeter Mi',
      source: 'src/image/videokaraoke/102029u6hebwoM08.jpg',
      date: '1 неделю назад',
      view: '2314',
    },
    {
      name: 'Tere Liye - Veer Zara',
      source: 'src/image/videokaraoke/102027gPYtiyPF16.jpg',
      date: '1 неделю назад',
      view: '1132',
    },
    {
      name: 'Bruno Mars & ROSE - APT.',
      source: 'src/image/videokaraoke/102026roOosqIM2G.jpg',
      date: '1 неделю назад',
      view: '1132',
    },
    {
      name: 'Tum Hi Ho Arijit Singh',
      source: 'src/image/videokaraoke/102022CdyN4CKUMu.jpg',
      date: '2 недели назад',
      view: '1046',
    },
    {
      name: 'Tere Liye Hum Hain Jiye ',
      source: 'src/image/videokaraoke/1020211PjHxjhrIe.jpg',
      date: '2 недели назад',
      view: '440',
    },
    {
      name: 'Jahan bagşy - Azara galma',
      source: 'src/image/videokaraoke/102020lb5E9MPbZw.jpg',
      date: '2 недели назад',
      view: '2714',
    },
  ],
  news: [
    {
      name: 'Watan Habarlary 12.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: ' 9 часов назад',
      view: '572',
    },
    {
      name: 'Watan Habarlary 11.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '1 день назад',
      view: '4347',
    },
    {
      name: 'Watan Habarlary 10.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '2 дня назад',
      view: '8665',
    },
    {
      name: 'Watan Habarlary 09.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '3 дня назад',
      view: '5210',
    },
    {
      name: 'Watan Habarlary 08.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '4 дня назад',
      view: '1767',
    },
    {
      name: 'Watan Habarlary 07.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '5 дней назад',
      view: '4247',
    },
    {
      name: 'Watan Habarlary 06.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '6 дней назад ',
      view: '1260',
    },
    {
      name: 'Watan Habarlary 05.02.2025',
      source: 'src/image/videonews/v.jpg',
      date: '1 неделю назад',
      view: '5984',
    },
  ],
  technology: [
    {
      name: 'Первый обзор Xiaomi 15 Pro (и просто 15) — такого не ожидал...',
      source: 'src/image/videoscience/101561lUTOS9TcWX.jpg',
      date: '3 месяца назад',
      view: '3686',
    },
    {
      name: 'Xiaomi 15 и HyperOS 2 — ну что, опять топ',
      source: 'src/image/videoscience/1015108oLgmdpWxh.jpg',
      date: '3 месяца назад',
      view: '2147',
    },
    {
      name: 'Türkmenistanda «E-mekdep» ulgamy işläp başlady',
      source: 'src/image/videoscience/101451MGGpmIw12g.jpg',
      date: '3 месяца назад',
      view: '504',
    },
    {
      name: '«E-mekdep» mümkinçilikleri',
      source: 'src/image/videoscience/100705cSKWN25n7Y.jpg',
      date: '3 месяца назад',
      view: '4130',
    },
    {
      name: '«E-mekdep» elektron dolandyryş ulgamy',
      source: 'src/image/videoscience/101448AFq6J0ArKp.jpg',
      date: '3 месяца назад',
      view: '3261',
    },
    {
      name: '«E-mekdep»',
      source: 'src/image/videoscience/101447PeCbNBI26I.jpg',
      date: '3 месяца назад',
      view: '8247',
    },
    {
      name: 'iOS 18 — крупнейшее обновление со времён iOS 7 (и калькулятор для iPad ещё)',
      source: 'src/image/videoscience/100712QspFxQZbeD.jpg',
      date: '2 года назад',
      view: '38065',
    },
    {
      name: 'BlackBerry 15 Pro — iPhone с',
      source: 'src/image/videoscience/100705cSKWN25n7Y.jpg',
      date: '2 года назад',
      view: '38984',
    },
  ],
  sport: [
    {
      name: 'ИСПАНИЯ - ПУТЬ К ТИТУЛУ ЕВРО 2024',
      source: 'src/image/videosport/1016730JKknXvHbT.jpg',
      date: '2 месяца назад',
      view: '12686',
    },
    {
      name: 'Muhammad Ali vs George Foreman',
      source: 'src/image/videosport/101653ZQb84kMHk4.jpg',
      date: '2 месяца назад',
      view: '17347',
    },
    {
      name: 'Хабиб Нурмагомедов vs Конор МакГрегор',
      source: 'src/image/videosport/101645ARPwhiRvDq.jpg',
      date: '2 месяца назад',
      view: '46665',
    },
    {
      name: 'Бой Майк Тайсон — Джейк Пол',
      source: 'src/image/videosport/101624S7nvnTIzSt.jpg',
      date: '3 месяца назад',
      view: '5210',
    },
    {
      name: 'MESSIAH - A Lionel Messi Movie',
      source: 'src/image/videosport/101440Ofsqn2UV4Y.jpg',
      date: '3 месяца назад',
      view: '11767',
    },
    {
      name: 'Lionel Messi - WORLD CHAMPION - Movie',
      source: 'src/image/videosport/101439tEG4aWC1uo.jpg',
      date: '3 месяца назад',
      view: '8247',
    },
    {
      name: 'F1 Race Highlights - 2024 Canadian Grand Prix',
      source: 'src/image/videosport/100781nS1ScDCpg0.jpg',
      date: ' 7 месяцев назад',
      view: '17260',
    },
    {
      name: '50 Messi Skills that Stopped the',
      source: 'src/image/videosport/100780ezhuKGCPaJ.jpg',
      date: ' 7 месяцев назад  ',
      view: '10984',
    },
  ],
}
export const nav = {
  main: ['Главная'],
  online: ['Онлайн ТВ'],
  movie: [
    'Топ Фильмы',
    'Военные',
    'Семейный',
    'Документальные',
    'Исторические',
    'Приключения',
    'Фантастика',
    'Комедийные',
    '2024',
    'Триллеры',
    'Детективы',
    'Боевики',
    'Для детей',
    'Драмы',
  ],
  music: [
    'Топ Исполнители',
    'Народная музыка',
    'Туркменская эстрада',
    'Фолк',
    '80-тые',
    'Классика ',
    'Латино-американская музыка',
    'Блюз',
    'Джаз',
    'Кантри',
    'Шансон романс',
    'Электронная музыка',
    'Рок',
    'Ска, рокстеди, регги',
    'Поп',
    'Рэп (Хип-хоп)',
    '90-тые',
    'Релакс',
    'Из мультфильмов',
    'Из кино',
    'Диско',
    'Эстрада',
    'Сборник',
  ],
  cartoon: [
    'Топ Мультфильмы',
    'Советские',
    'Аниме',
    'Для взрослых',
    'Для детей',
    'Полнометражные',
    'Приключения',
    'Развивающие',
    'Сериалы',
  ],
  library: [
    'Top Книги',
    'Edebiýat',
    'Fizika',
    'Biologiýa',
    'Taryh',
    'Informatika',
    'Çeper eser',
    'Iňlis dili',
    'Lukmançylyk we saglyk',
    'Programmirleme',
    'Ykdysadyýet',
    'Umumy',
    'Täze tehnologiýa',
    'Işewürlik',
    'Senagat',
    'Aşhana',
    'Filosofiýa',
    'Başdan geçirme',
    'Syýasat',
    'Žurnalistika',
    'Sungat',
    'Ekologiýa',
    'Žurnallar',
    'Türkmen dili',
    'Matematika',
    'Himiýa',
    'Geografiýa',
    'Astronomiýa',
    'Daşary ýurt dili',
    'Goşgy',
    'Rus dili',
    ' Çagalar üçin',
    'Geometriýa',
    'Psihologiýa-pedagogika',
    'Sport we fitnes',
    'Gurluşyk',
    'Degişme-gülki',
    'Roman',
    'Ensiklopediýa',
    'Kosmetologiýa',
    'Hukuk',
    'Biografiýa',
    'Oba hojalyk',
    'Syýahat',
    'Gazetler',
  ],
  video: [
    'Топ',
    'Клипы',
    'Туркменские песни',
    'Узбекские песни',
    'Русские песни',
    'Латинские песни',
    'Индийские песни',
    'Турецский песни',
    'Гитара',
    'Рок',
    'Поп',
    'Ремикси',
    'Арабские песни',
    'Живой музыка',
    'Новые песни',
    'Народные песни',
    'Хип Хоп',
    'Консерти',
    'Пианино',
    'Музыкалъный хити',
  ],
  comedy: [
    'Топ Юмор',
    'Передачи',
    'Юмористические ролики',
    'Для детей',
    'Comedy club',
    'Маски шоу',
    'Ералаш',
    'Комики',
  ],
  cook: [
    'Топ Вкусно',
    'Супы',
    'Закуски',
    'Салаты',
    'Pыба и морепродукты',
    'Мясные блюда',
    'Куриные блюда',
    'Шашлыки',
    'Стейки',
    'Фастфуд',
    'Десерты',
    'Блюда из теста',
    'Напитки',
    'Национальные блюда',
  ],
  health: [
    'Топ Здоровье',
    'Народная медицина',
    'Фармацевтика',
    'Передовые технологии',
    'Косметология',
    'Гимнастика для здоровья',
    'Правильное питание и диета',
    'Офтальмология',
    'ЛОР',
    'Педиатрия',
    'Терапевтия',
    'Хирургия',
    'Лекции и учебные справочники',
    'Психология',
    'Массаж',
    'Передачи о здоровье',
    'Йога',
    'Лечебная физическая культура',
    'Про болезни',
    'Зачатие у человека',
    'Стоматология',
    'Онкология',
    'Клинические разделы медицины',
  ],
  technology: [
    'Топ технология',
    'Обучение детей',
    'Уроки для школьников',
    'Лекции Иностранный язык',
    'Уроки музыки и танцев',
    'Программирование',
    'Инновационные технологии',
    'История',
    'Наука',
    'Правило дорожного движения',
    'Учебные заведения',
    'Изобретение',
    'Технология Робототехника',
    'Ноу-хау',
    'Естественные науки',
    'Социология',
    'Автоматизация',
    'Транспорт и Транспортировка Производство',
    'Телекоммуникационные технологии',
    'Компьютерная техника',
  ],
  interest: [
    'Топ Интересное',
    'Путешествия',
    'Животный мир',
    'Растительный мир',
    'Лайфхаки',
    'Авто',
    'Культура',
    'Финанс и бизнес',
    'Космос',
    'Охота и рыбалка',
    'Строительство и ремонт',
    'Развлечения',
    'Интересные открытия',
    'Интересные передачи и шоу',
  ],
  karaoke: [
    'Топ Караоке',
    'Туркменские песни',
    'Народные песни',
    'Русские песни',
    'Узбекские песни',
    'Турецский песни',
    'Шансон, романс',
    'Зарубежные песни',
    'Ресторанные песни',
    'Новогодние песни',
    'С днем ​рождения',
    'Детские песни',
    'Песни из кино',
    'Военные песни',
    'Казахские песни',
    'Кыргызские песни',
    'Татарские песни',
    'Армянские песни',
    'Азербайджанские песни',
  ],
  news: [
    '01.02.2025',
    '02.02.2025',
    '03.02.2025',
    '04.02.2025',
    '05.02.2025',
    '06.02.2025',
    '07.02.2025',
    '08.02.2025',
    '09.02.2025',
    '10.02.2025',
    '11.02.2025',
    '12.02.2025',
    '13.02.2025',
  ],
  sport: [
    'Топ Спорт',
    'Футбол',
    'Баскетбол',
    'Волейбол',
    'Теннис',
    'Боевые искусства',
    'Легкая атлетика',
    'Тяжелая атлетика',
    'Водные виды спорта',
    'Автогонки',
    'Стратегическая игра',
    'Киберспорт',
    'Олимпийских играх',
    'Новости спорта',
    'Чемпионаты',
  ],
}
export const menuMain = {
  main: 'Главная',
  online: 'Онлайн ТВ',
  movie: 'Фильмы',
  music: 'Песни',
  cartoon: 'Мультфильмы',
  library: 'Библиотека',
  video: 'Клипы',
  karaoke: 'Караоке',
  cook: 'Вкусно',
  comedy: 'Юмор',
  health: 'Здоровье',
  technology: 'Наука и технология',
  sport: 'Спорт',
  interest: 'Интересное',
  news: 'Watan habarlary',
}
export const mainGrid = {
  main: 'Главная',
  online: 'Онлайн ТВ',
  movie: 'grid-cols-6',
  music: 'grid-cols-4',
  cartoon: 'grid-cols-4',
  library: 'grid-cols-6',
  video: 'grid-cols-4',
  karaoke: 'grid-cols-4',
  cook: 'grid-cols-4',
  comedy: 'grid-cols-4',
  health: 'grid-cols-4',
  technology: 'grid-cols-4',
  sport: 'grid-cols-4',
  interest: 'grid-cols-4',
  news: 'grid-cols-4',
}
export const alpEn = [
  '0-9',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'R',
  'Q',
  'S',
  'T',
  'V',
  'W',
  'X',
  'Y',
  'Z',
]
export const alpRu = [
  'А',
  'Б',
  'В',
  'Г',
  'Д',
  'Е',
  'Ё',
  'Ж',
  'З',
  'И',
  'Й',
  'К',
  'Л',
  'М',
  'Н',
  'О',
  'П',
  'Р',
  'С',
  'Т',
  'У',
  'Ф',
  'Х',
  'Ц',
  'Ш',
  'Щ',
  'Ы',
  'Э',
  'Ю',
  'Я',
]
export const fanBook = [
  {
    source: '/src/image/library/evlenmeden_once.jpg',
    name: 'Evlenmeden önce',
    author: 'Doğan Cüceloğlu',
    category: 'Psihologiýa-pedagogika',
    size: '5.63 МБ',
    view: '16681',
  },
  {
    source: '/src/image/library/olenden_kim_aglar.jpg',
    name: 'Öleňde kim aglar',
    author: 'Robin Şarma',
    category: 'Psihologiýa-pedagogika',
    size: '1.93 МБ',
    view: '16660',
  },
  {
    source: '/src/image/library/aldanan_mojek.jpg',
    name: 'Aldanan möjek',
    author: '',
    category: 'Çagalar üçin',
    size: '1.45 МБ',
    view: '14115',
  },
  {
    source: '/src/image/library/turkmeniya.jpg',
    name: '    Туркмения и туркмены / Туркмения и туркмены',
    author: 'Куропаткин А. Н.',
    category: 'Taryh',
    size: '22.71 МБ',
    view: '12071',
  },
  {
    source: '/src/image/library/turkmen_dili.jpg',
    name: 'Туркменский язык',
    author: 'Э.А. Грунина',
    category: 'Türkmen dili',
    size: '89.84 МБ',
    view: '16149',
  },
  {
    source: '/src/image/library/oylan_hem_baya.jpg',
    name: 'Oýlan hem baýa',
    author: 'Napoleon HILL',
    category: 'Işewürlik',
    size: '1.32 МБ',
    view: '11831',
  },
]
export const menuHeader = {
  main: 'Главная',
  online: 'Онлайн ТВ',
  movie: 'Фильмы',
  music: 'Песни',
  cartoon: 'Мультфильмы',
  library: 'Библиотека',
  anyMenu: 'Другие',
}
export const anyMenuHeader = {
  video: 'Клипы',
  karaoke: 'Караоке',
  cook: 'Вкусно',
  comedy: 'Юмор',
  health: 'Здоровье',
  technology: 'Наука и технология',
  sport: 'Спорт',
  interest: 'Интересное',
  news: 'Watan habarlary',
}
export const menuOnline = [
  {
    name: 'Altyn Asyr',
    imgUrl: '',
  },
  {
    name: 'Ýaşlyk',
    imgUrl: 'dfdf',
  },
  {
    name: 'Miras',
    imgUrl: 'dfdf',
  },
  {
    name: 'Türkmenistan',
    imgUrl: 'dfdf',
  },
  {
    name: 'Türkmen owazy',
    imgUrl: 'dfdf',
  },
  {
    name: 'Aşgabat',
    imgUrl: 'dfdf',
  },
  {
    name: 'Türkmen Sport',
    imgUrl: 'dfdf',
  },
  {
    name: 'Матч ТВ',
    imgUrl: 'dfdf',
  },
  {
    name: 'СТС',
    imgUrl: 'dfdf',
  },
  {
    name: 'Euronews',
    imgUrl: 'dfdf',
  },
  {
    name: 'TNT Music',
    imgUrl: 'dfdf',
  },
  {
    name: 'ТНТ',
    imgUrl: 'dfdf',
  },
  {
    name: 'Пятница',
    imgUrl: 'dfdf',
  },
  {
    name: 'IDMAN',
    imgUrl: 'dfdf',
  },
  {
    name: 'МУЛЬТ',
    imgUrl: 'dfdf',
  },
  {
    name: 'Show TV',
    imgUrl: 'dfdf',
  },
  {
    name: 'VostokTV',
    imgUrl: 'dfdf',
  },
  {
    name: 'Kanal D',
    imgUrl: 'dfdf',
  },
  {
    name: 'Россия 24',
    imgUrl: 'dfdf',
  },
  {
    name: 'Домашний',
    imgUrl: 'dfdf',
  },
  {
    name: 'Звезда',
    imgUrl: 'dfdf',
  },
  {
    name: 'МУЗ ТВ',
    imgUrl: 'dfdf',
  },
  {
    name: 'Варзиш',
    imgUrl: 'dfdf',
  },
  {
    name: 'ATV',
    imgUrl: 'dfdf',
  },
  {
    name: 'Mатч боец',
    imgUrl: 'dfdf',
  },
  {
    name: 'Первый канал',
    imgUrl: 'dfdf',
  },
  {
    name: 'НТВ',
    imgUrl: 'dfdf',
  },
  {
    name: 'Че',
    imgUrl: 'dfdf',
  },
  {
    name: 'Star TV',
    imgUrl: 'dfdf',
  },
  {
    name: 'Kanal 7',
    imgUrl: 'dfdf',
  },
  {
    name: 'Ren TV',
    imgUrl: 'dfdf',
  },
  {
    name: 'Music Box Ru',
    imgUrl: 'dfdf',
  },
  {
    name: 'Footboll HD',
    imgUrl: 'dfdf',
  },
  {
    name: 'Дикая охота',
    imgUrl: 'dfdf',
  },
  {
    name: 'Жара TV',
    imgUrl: 'dfdf',
  },
  {
    name: 'Minika Cocuk',
    imgUrl: 'dfdf',
  },
  {
    name: 'O2 TV',
    imgUrl: 'dfdf',
  },
  {
    name: 'Kanal DMAX',
    imgUrl: 'dfdf',
  },
  {
    name: 'TV8',
    imgUrl: 'dfdf',
  },
  {
    name: 'Россия 1',
    imgUrl: 'dfdf',
  },
  {
    name: 'РБК',
    imgUrl: 'dfdf',
  },
  {
    name: 'Тв3',
    imgUrl: 'dfdf',
  },
  {
    name: 'СТС +4',
    imgUrl: 'dfdf',
  },
  {
    name: 'Kinoteatr',
    imgUrl: 'dfdf',
  },
  {
    name: 'ФУТБОЛ 1',
    imgUrl: 'dfdf',
  },
  {
    name: 'МИР24',
    imgUrl: 'dfdf',
  },
  {
    name: 'Mono Tv',
    imgUrl: 'dfdf',
  },
]
export const any = [
  {
    name: 'Клипы',
    imgUrl: '/src/image/any_menu/video.png',
    id: 'video',
  },
  {
    name: 'Караоке',
    imgUrl: '/src/image/any_menu/karaoke.png',
    id: 'karaoke',
  },
  {
    name: 'Вкусно',
    imgUrl: '/src/image/any_menu/cook.png',
    id: 'cook',
  },
  {
    name: 'Юмор',
    imgUrl: '/src/image/any_menu/comedy.png',
    id: 'comedy',
  },
  {
    name: 'Здоровье',
    imgUrl: '/src/image/any_menu/health.png',
    id: 'health',
  },
  {
    name: 'Наука и технология',
    imgUrl: '/src/image/any_menu/science.png',
    id: 'technology',
  },
  {
    name: 'Спорт',
    imgUrl: '/src/image/any_menu/sport.png',
    id: 'sport',
  },
  {
    name: 'Интересное',
    imgUrl: '/src/image/any_menu/int.png',
    id: 'interest',
  },
  {
    name: 'Watan habarlary',
    imgUrl: '/src/image/any_menu/news.png',
    id: 'news',
  },
]
export const series = [
  'Топ Сериалы',
  'Военные',
  'Исторические',
  'Криминальные',
  'Приключения',
  'Романтические',
  'Драмы',
  '2024',
  'Детективы',
  'Комедийные',
  'Мелодрамы',
  'Медицинские',
  'Триллеры',
  'Фантастические',
  'Боевики',
]
export const mainMovie1 = [
  {
    name: 'Daragt',
    source: '/src/image/movie/daragt_main.jpg',
    time: '01:20:36',
    genre: 'драмы',
    date: '2 года назад',
    rating: 5,
    view: 312688,
  },
  {
    name: 'Araçynyň Ady | Türkmen Filmi(2025)',
    source: '/src/image/movie/images (2).jpg',
    time: '01:12:30',
    genre: 'драмы',
    date: '2 месяцев назад',
    rating: 5,
    view: 138667,
  },
  {
    name: 'Diri Galan - Выживший',
    source: '/src/image/movie/the_revenant_main.jpg',
    time: '02:37:35',
    genre: 'драмы',
    date: '1 год назад',
    rating: 5,
    view: 292393,
  },
  {
    name: 'Дэдпул и Росомаха (2024)',
    source: '/src/image/movie/wolverina_deadpool_main.jpg',
    time: '02:07:38',
    genre: 'боевик',
    date: '7 месяцев назад',
    rating: 5,
    view: 289041,
  },
]
export const mainMovie2 = [
  {
    name: 'Hemmezat gowlyga | Turkmen Filmi (2024)',
    source: '/src/image/movie/gowlyga.jpg',
    time: '01:14:38',
    genre: 'драмы',
    date: '6 месяцев назад',
    rating: 5,
    view: 304483,
  },
  {
    name: 'Forsazh - Örän güýçli tizlikde : Hobs we Şou',
    source: '/src/image/movie/hobs_shaw_main.jpg',
    time: '02:17:25',
    genre: 'боевик',
    date: '1 год  назад',
    rating: 5,
    view: 308414,
  },
  {
    name: 'Граф Монте - Гриста (2024)',
    source: '/src/image/movie/monte-cristo.jpeg',
    time: '02:57:48',
    genre: 'боевик',
    date: '6 месяцев назад',
    rating: 5,
    view: 91623,
  },
  {
    name: '7/24',
    source: '/src/image/movie/taxi_banner.jpg',
    date: '2 года назад',
    rating: 5,
    view: 74540,
  },
]
export const mainMovieTable = [
  {
    name: 'Daragt',
    source: '/src/image/movie/daragt.jpg',
  },
  {
    name: 'Araçynyň Ady',
    source: '/src/image/movie/aracynyn_ady.jpg',
  },
  {
    name: 'Diri Galan',
    source: '/src/image/movie/the_revenant.jpg',
  },
  {
    name: 'Дедпул и Росомаха',
    source: '/src/image/movie/wolverina_deadpool.jpg',
  },
  {
    name: 'Hemmezat gowlyga',
    source: '/src/image/movie/gowlyga.jpg',
  },
  {
    name: 'Forsazh - Örän güýçli tizlikde : Hobs we Şou',
    source: '/src/image/movie/hobs_shaw.jpg',
  },
  {
    name: 'Граф Монте Гриста',
    source: '/src/image/movie/graf_monte_krista.jpg',
  },
  {
    name: 'Taksi hyzmaty',
    source: '/src/image/movie/taksi_hyzmaty.jpg',
  },
]
